// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
    billboard: dynamic(() => import('./Billboard')),
    cta_banner: dynamic(() => import('./CtaBanner')),
    intro: dynamic(() => import('./Intro')),
    lookbook: dynamic(() => import('./Lookbook')),
    poster: dynamic(() => import('./Poster')),
    swiper: dynamic(() => import('./Swiper')),
};
