// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type CollectionDocumentDataSlicesSlice = never;

type CollectionDocumentDataSlices2Slice = SwiperSlice | BillboardSlice;

type CollectionDocumentDataSlices3Slice = SwiperSlice | BillboardSlice;

type CollectionDocumentDataSlices4Slice = PosterSlice;

/**
 * Content for Collection documents
 */
interface CollectionDocumentData {
    /**
     * Slice Zone field in *Collection*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: collection.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<CollectionDocumentDataSlicesSlice>
    /**
     * Meta Description field in *Collection*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: collection.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */;
    meta_description: prismic.KeyTextField;

    /**
     * Meta Image field in *Collection*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: collection.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>;

    /**
     * Meta Title field in *Collection*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: collection.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_title: prismic.KeyTextField
    /**
     * Top Breakout Image field in *Collection*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: collection.top_breakout_image
     * - **Tab**: Above Grid
     * - **Documentation**: https://prismic.io/docs/field#image
     */;
    top_breakout_image: prismic.ImageField<never>;

    /**
     * Slice Zone field in *Collection*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: collection.slices2[]
     * - **Tab**: Above Grid
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices2: prismic.SliceZone<CollectionDocumentDataSlices2Slice>
    /**
     * Slice Zone field in *Collection*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: collection.slices3[]
     * - **Tab**: Below Grid
     * - **Documentation**: https://prismic.io/docs/field#slices
     */;
    slices3: prismic.SliceZone<CollectionDocumentDataSlices3Slice>
    /**
     * Slice Zone field in *Collection*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: collection.slices4[]
     * - **Tab**: Grid Disruptors
     * - **Documentation**: https://prismic.io/docs/field#slices
     */;
    slices4: prismic.SliceZone<CollectionDocumentDataSlices4Slice>;
}

/**
 * Collection document from Prismic
 *
 * - **API ID**: `collection`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CollectionDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithUID<
        Simplify<CollectionDocumentData>,
        'collection',
        Lang
    >;

type ContentLibraryDocumentDataSlicesSlice =
    | IntroSlice
    | LookbookSlice
    | CtaBannerSlice
    | BillboardSlice
    | SwiperSlice
    | PosterSlice;

/**
 * Content for Content Library documents
 */
interface ContentLibraryDocumentData {
    /**
     * Slice Zone field in *Content Library*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: content-library.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<ContentLibraryDocumentDataSlicesSlice>;
}

/**
 * Content Library document from Prismic
 *
 * - **API ID**: `content-library`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContentLibraryDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithUID<
        Simplify<ContentLibraryDocumentData>,
        'content-library',
        Lang
    >;

type LandingPageDocumentDataSlicesSlice =
    | IntroSlice
    | LookbookSlice
    | SwiperSlice
    | PosterSlice
    | CtaBannerSlice
    | BillboardSlice;

/**
 * Content for Landing Page documents
 */
interface LandingPageDocumentData {
    /**
     * Slice Zone field in *Landing Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<LandingPageDocumentDataSlicesSlice>
    /**
     * Meta Title field in *Landing Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: landing_page.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */;
    meta_title: prismic.KeyTextField;

    /**
     * Meta Description field in *Landing Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: landing_page.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_description: prismic.KeyTextField;

    /**
     * Meta Image field in *Landing Page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>;
}

/**
 * Landing Page document from Prismic
 *
 * - **API ID**: `landing_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithUID<
        Simplify<LandingPageDocumentData>,
        'landing_page',
        Lang
    >;

type ProductDocumentDataSlicesSlice = CtaBannerSlice;

/**
 * Content for Product documents
 */
interface ProductDocumentData {
    /**
     * Slice Zone field in *Product*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: product.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<ProductDocumentDataSlicesSlice>
    /**
     * Meta Description field in *Product*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: product.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */;
    meta_description: prismic.KeyTextField;

    /**
     * Meta Image field in *Product*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: product.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>;

    /**
     * Meta Title field in *Product*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: product.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_title: prismic.KeyTextField;
}

/**
 * Product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithUID<
        Simplify<ProductDocumentData>,
        'product',
        Lang
    >;

/**
 * Item in *Product Information → Measurement Instructions*
 */
export interface ProductInformationDocumentDataMeasurementInstructionsItem {
    /**
     * Body Part field in *Product Information → Measurement Instructions*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: product_information.measurementInstructions[].bodyPart
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    bodyPart: prismic.RichTextField;

    /**
     * Instruction field in *Product Information → Measurement Instructions*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: product_information.measurementInstructions[].instruction
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    instruction: prismic.RichTextField;
}

/**
 * Item in *Product Information → Delivery Info*
 */
export interface ProductInformationDocumentDataDeliveryInfoItem {
    /**
     * Title field in *Product Information → Delivery Info*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: product_information.deliveryInfo[].title
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    title: prismic.TitleField;

    /**
     * Description field in *Product Information → Delivery Info*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: product_information.deliveryInfo[].description
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    description: prismic.RichTextField;
}

/**
 * Content for Product Information documents
 */
interface ProductInformationDocumentData {
    /**
     * Title field in *Product Information*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: E.g. Men's Sizing Guide
     * - **API ID Path**: product_information.title
     * - **Tab**: Size Guide
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    title: prismic.RichTextField;

    /**
     * Description field in *Product Information*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: E.g. Use the measurements below to...
     * - **API ID Path**: product_information.description
     * - **Tab**: Size Guide
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    description: prismic.RichTextField;

    /**
     * Context field in *Product Information*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: E.g. Includes short sleeve jerseys, long sleeve jerseys, base layers, tee's and jackets
     * - **API ID Path**: product_information.context
     * - **Tab**: Size Guide
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    context: prismic.RichTextField;

    /**
     * Image field in *Product Information*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: product_information.image
     * - **Tab**: Size Guide
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image: prismic.ImageField<never>;

    /**
     * Measurement Instructions field in *Product Information*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: product_information.measurementInstructions[]
     * - **Tab**: Size Guide
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    measurementInstructions: prismic.GroupField<
        Simplify<ProductInformationDocumentDataMeasurementInstructionsItem>
    >
    /**
     * Warranty Title field in *Product Information*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: product_information.warrantyTitle
     * - **Tab**: Warranty
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */;
    warrantyTitle: prismic.TitleField;

    /**
     * Warranty Description field in *Product Information*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: product_information.warrantyDescription
     * - **Tab**: Warranty
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    warrantyDescription: prismic.RichTextField
    /**
     * Delivery Info field in *Product Information*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: product_information.deliveryInfo[]
     * - **Tab**: Delivery Info
     * - **Documentation**: https://prismic.io/docs/field#group
     */;
    deliveryInfo: prismic.GroupField<
        Simplify<ProductInformationDocumentDataDeliveryInfoItem>
    >;
}

/**
 * Product Information document from Prismic
 *
 * - **API ID**: `product_information`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductInformationDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithUID<
        Simplify<ProductInformationDocumentData>,
        'product_information',
        Lang
    >;

export type AllDocumentTypes =
    | CollectionDocument
    | ContentLibraryDocument
    | LandingPageDocument
    | ProductDocument
    | ProductInformationDocument;

/**
 * Primary content in *Billboard → Primary*
 */
export interface BillboardSliceStaticPrimary {
    /**
     * Desktop Image field in *Billboard → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: billboard.primary.desktop_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    desktop_image: prismic.ImageField<never>;

    /**
     * Mobile Image field in *Billboard → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: billboard.primary.mobile_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    mobile_image: prismic.ImageField<never>;

    /**
     * Content Position field in *Billboard → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Bottom Left
     * - **API ID Path**: billboard.primary.content_position
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    content_position: prismic.SelectField<'Bottom Left' | 'Center', 'filled'>;

    /**
     * Title field in *Billboard → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: billboard.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * Title Size field in *Billboard → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Large
     * - **API ID Path**: billboard.primary.title_size
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    title_size: prismic.SelectField<'Large' | 'Medium' | 'Small', 'filled'>;

    /**
     * Subtitle field in *Billboard → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: billboard.primary.sub_title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    sub_title: prismic.KeyTextField;

    /**
     * Subtitle Sizes field in *Billboard → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Large
     * - **API ID Path**: billboard.primary.sub_title_size
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    sub_title_size: prismic.SelectField<'Large' | 'Medium' | 'Small', 'filled'>;

    /**
     * Contain Around Image field in *Billboard → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: billboard.primary.contain_around_image
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    contain_around_image: prismic.BooleanField;
}

/**
 * Primary content in *Billboard → Items*
 */
export interface BillboardSliceStaticItem {
    /**
     * Button Variant field in *Billboard → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Base
     * - **API ID Path**: billboard.items[].button_variant
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_variant: prismic.SelectField<
        'Base' | 'Ghost' | 'Secondary' | 'Text' | 'Quite',
        'filled'
    >;

    /**
     * Button Label field in *Billboard → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Discover
     * - **API ID Path**: billboard.items[].button_label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_label: prismic.KeyTextField;

    /**
     * Button Link field in *Billboard → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: billboard.items[].button_link
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_link: prismic.KeyTextField;

    /**
     * Button Icon field in *Billboard → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: billboard.items[].button_icon
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_icon: prismic.SelectField<
        '-' | 'Globe' | 'Discover' | 'Northeast' | 'Right' | 'Left'
    >;
}

/**
 * Static variation for Billboard Slice
 *
 * - **API ID**: `static`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BillboardSliceStatic = prismic.SharedSliceVariation<
    'static',
    Simplify<BillboardSliceStaticPrimary>,
    Simplify<BillboardSliceStaticItem>
>;

/**
 * Primary content in *Billboard → Items*
 */
export interface BillboardSliceCarouselItem {
    /**
     * Desktop Image field in *Billboard → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: billboard.items[].desktop_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    desktop_image: prismic.ImageField<never>;

    /**
     * Mobile Image field in *Billboard → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: billboard.items[].mobile_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    mobile_image: prismic.ImageField<never>;

    /**
     * Content Position field in *Billboard → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Bottom Left
     * - **API ID Path**: billboard.items[].content_position
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    content_position: prismic.SelectField<'Bottom Left' | 'Center', 'filled'>;

    /**
     * Title field in *Billboard → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: billboard.items[].title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * Title Size field in *Billboard → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Large
     * - **API ID Path**: billboard.items[].title_size
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    title_size: prismic.SelectField<'Large' | 'Medium' | 'Small', 'filled'>;

    /**
     * Subtitle field in *Billboard → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: billboard.items[].subtitle
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    subtitle: prismic.KeyTextField;

    /**
     * Subtitle Size field in *Billboard → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Large
     * - **API ID Path**: billboard.items[].subtitle_size
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    subtitle_size: prismic.SelectField<'Large' | 'Medium' | 'Small', 'filled'>;

    /**
     * Button 1 Label field in *Billboard → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: billboard.items[].button_1_label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_1_label: prismic.KeyTextField;

    /**
     * Button 1 Link field in *Billboard → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: billboard.items[].button_1_link
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_1_link: prismic.KeyTextField;

    /**
     * Button 1 Variant field in *Billboard → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Base
     * - **API ID Path**: billboard.items[].button_1_variant
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_1_variant: prismic.SelectField<
        'Base' | 'Ghost' | 'Secondary' | 'Text' | 'Quite',
        'filled'
    >;

    /**
     * Button 1 Icon field in *Billboard → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: billboard.items[].button_1_icon
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_1_icon: prismic.SelectField<
        '-' | 'Globe' | 'Discover' | 'Northeast' | 'Right' | 'Left'
    >;

    /**
     * Button 2 Label field in *Billboard → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: billboard.items[].button_2_label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_2_label: prismic.KeyTextField;

    /**
     * Button 2 Link field in *Billboard → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: billboard.items[].button_2_link
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_2_link: prismic.KeyTextField;

    /**
     * Button 2 Variant field in *Billboard → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Base
     * - **API ID Path**: billboard.items[].button_2_variant
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_2_variant: prismic.SelectField<
        'Base' | 'Ghost' | 'Secondary' | 'Text' | 'Quite',
        'filled'
    >;

    /**
     * Button 2 Icon field in *Billboard → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: billboard.items[].button_2_icon
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_2_icon: prismic.SelectField<
        '-' | 'Globe' | 'Discover' | 'Northeast' | 'Right' | 'Left'
    >;

    /**
     * Button 3 Label field in *Billboard → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: billboard.items[].button_3_label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_3_label: prismic.KeyTextField;

    /**
     * Button 3 Link field in *Billboard → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: billboard.items[].button_3_link
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_3_link: prismic.KeyTextField;

    /**
     * Button 3 Variant field in *Billboard → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Base
     * - **API ID Path**: billboard.items[].button_3_variant
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_3_variant: prismic.SelectField<
        'Base' | 'Ghost' | 'Secondary' | 'Text' | 'Quite',
        'filled'
    >;

    /**
     * Button 3 Icon field in *Billboard → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: billboard.items[].button_3_icon
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_3_icon: prismic.SelectField<
        '-' | 'Globe' | 'Discover' | 'Northeast' | 'Right' | 'Left'
    >;
}

/**
 * Carousel variation for Billboard Slice
 *
 * - **API ID**: `carousel`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BillboardSliceCarousel = prismic.SharedSliceVariation<
    'carousel',
    Record<string, never>,
    Simplify<BillboardSliceCarouselItem>
>;

/**
 * Slice variation for *Billboard*
 */
type BillboardSliceVariation = BillboardSliceStatic | BillboardSliceCarousel;

/**
 * Billboard Shared Slice
 *
 * - **API ID**: `billboard`
 * - **Description**: Billboard Static
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BillboardSlice = prismic.SharedSlice<
    'billboard',
    BillboardSliceVariation
>;

/**
 * Primary content in *CtaBanner → Primary*
 */
export interface CtaBannerSliceSinglePrimary {
    /**
     * Desktop Image field in *CtaBanner → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: cta_banner.primary.desktop_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    desktop_image: prismic.ImageField<never>;

    /**
     * Mobile Image field in *CtaBanner → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: cta_banner.primary.mobile_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    mobile_image: prismic.ImageField<never>;

    /**
     * Title field in *CtaBanner → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: cta_banner.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * Title Size field in *CtaBanner → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: cta_banner.primary.title_size
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    title_size: prismic.SelectField<'Large' | 'Medium' | 'Small'>;

    /**
     * Title Icon field in *CtaBanner → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Northeast
     * - **API ID Path**: cta_banner.primary.title_icon
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    title_icon: prismic.SelectField<
        'Northeast' | 'Globe' | 'Discover' | 'Right' | 'Left',
        'filled'
    >;

    /**
     * Link field in *CtaBanner → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: cta_banner.primary.link
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    link: prismic.KeyTextField;
}

/**
 * Single variation for CtaBanner Slice
 *
 * - **API ID**: `single`
 * - **Description**: Single (One Up) Banner.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaBannerSliceSingle = prismic.SharedSliceVariation<
    'single',
    Simplify<CtaBannerSliceSinglePrimary>,
    never
>;

/**
 * Primary content in *CtaBanner → Items*
 */
export interface CtaBannerSliceSplitItem {
    /**
     * Desktop Image field in *CtaBanner → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: cta_banner.items[].desktop_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    desktop_image: prismic.ImageField<never>;

    /**
     * Mobile Image field in *CtaBanner → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: cta_banner.items[].mobile_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    mobile_image: prismic.ImageField<never>;

    /**
     * Title field in *CtaBanner → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: cta_banner.items[].title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * Title Size field in *CtaBanner → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: cta_banner.items[].title_size
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    title_size: prismic.SelectField<'Large' | 'Medium' | 'Small'>;

    /**
     * Title Icon field in *CtaBanner → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Northeast
     * - **API ID Path**: cta_banner.items[].title_icon
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    title_icon: prismic.SelectField<
        'Northeast' | 'Discover' | 'Globe' | 'Right' | 'Left',
        'filled'
    >;

    /**
     * Link field in *CtaBanner → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: cta_banner.items[].link
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    link: prismic.KeyTextField;
}

/**
 * Split variation for CtaBanner Slice
 *
 * - **API ID**: `split`
 * - **Description**: Single (One Up) Banner.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaBannerSliceSplit = prismic.SharedSliceVariation<
    'split',
    Record<string, never>,
    Simplify<CtaBannerSliceSplitItem>
>;

/**
 * Slice variation for *CtaBanner*
 */
type CtaBannerSliceVariation = CtaBannerSliceSingle | CtaBannerSliceSplit;

/**
 * CtaBanner Shared Slice
 *
 * - **API ID**: `cta_banner`
 * - **Description**: CtaBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaBannerSlice = prismic.SharedSlice<
    'cta_banner',
    CtaBannerSliceVariation
>;

/**
 * Primary content in *Intro → Primary*
 */
export interface IntroSliceDefaultPrimary {
    /**
     * Context field in *Intro → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: intro.primary.context
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    context: prismic.KeyTextField;

    /**
     * Sub Count field in *Intro → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: intro.primary.sub_count
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    sub_count: prismic.KeyTextField;

    /**
     * Content field in *Intro → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: intro.primary.content
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    content: prismic.KeyTextField;
}

/**
 * Default variation for Intro Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<IntroSliceDefaultPrimary>,
    never
>;

/**
 * Slice variation for *Intro*
 */
type IntroSliceVariation = IntroSliceDefault;

/**
 * Intro Shared Slice
 *
 * - **API ID**: `intro`
 * - **Description**: Intro
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroSlice = prismic.SharedSlice<'intro', IntroSliceVariation>;

/**
 * Primary content in *Lookbook → Primary*
 */
export interface LookbookSliceDefaultPrimary {
    /**
     * Context field in *Lookbook → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: lookbook.primary.context
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    context: prismic.KeyTextField;
}

/**
 * Primary content in *Lookbook → Items*
 */
export interface LookbookSliceDefaultItem {
    /**
     * Context field in *Lookbook → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Woman
     * - **API ID Path**: lookbook.items[].context
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    context: prismic.SelectField<'Woman' | 'Man', 'filled'>;

    /**
     * Desktop Image field in *Lookbook → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: lookbook.items[].desktop_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    desktop_image: prismic.ImageField<never>;

    /**
     * Mobile Image field in *Lookbook → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: lookbook.items[].mobile_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    mobile_image: prismic.ImageField<never>;

    /**
     * Heading field in *Lookbook → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: lookbook.items[].heading
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    heading: prismic.KeyTextField;

    /**
     * Product Handle 1 field in *Lookbook → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: lookbook.items[].product_handle_1
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    product_handle_1: prismic.KeyTextField;

    /**
     * Product Title 1 field in *Lookbook → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: lookbook.items[].product_title_1
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    product_title_1: prismic.KeyTextField;

    /**
     * Variant Title 1 field in *Lookbook → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: lookbook.items[].variant_title_1
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    variant_title_1: prismic.KeyTextField;

    /**
     * Product Handle 2 field in *Lookbook → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: lookbook.items[].product_handle_2
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    product_handle_2: prismic.KeyTextField;

    /**
     * Product Title 2 field in *Lookbook → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: lookbook.items[].product_title_2
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    product_title_2: prismic.KeyTextField;

    /**
     * Variant Title 2 field in *Lookbook → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: lookbook.items[].variant_title_2
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    variant_title_2: prismic.KeyTextField;

    /**
     * Product Handle 3 field in *Lookbook → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: lookbook.items[].product_handle_3
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    product_handle_3: prismic.KeyTextField;

    /**
     * Product Title 3 field in *Lookbook → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: lookbook.items[].product_title_3
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    product_title_3: prismic.KeyTextField;

    /**
     * Variant Title 3 field in *Lookbook → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: lookbook.items[].variant_title_3
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    variant_title_3: prismic.KeyTextField;

    /**
     * Product Handle 4 field in *Lookbook → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: lookbook.items[].product_handle_4
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    product_handle_4: prismic.KeyTextField;

    /**
     * Product Title 4 field in *Lookbook → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: lookbook.items[].product_title_4
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    product_title_4: prismic.KeyTextField;

    /**
     * Variant Title 4 field in *Lookbook → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: lookbook.items[].variant_title_4
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    variant_title_4: prismic.KeyTextField;
}

/**
 * Default variation for Lookbook Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LookbookSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<LookbookSliceDefaultPrimary>,
    Simplify<LookbookSliceDefaultItem>
>;

/**
 * Slice variation for *Lookbook*
 */
type LookbookSliceVariation = LookbookSliceDefault;

/**
 * Lookbook Shared Slice
 *
 * - **API ID**: `lookbook`
 * - **Description**: Lookbook
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LookbookSlice = prismic.SharedSlice<
    'lookbook',
    LookbookSliceVariation
>;

/**
 * Primary content in *Poster → Primary*
 */
export interface PosterSliceOneUpPrimary {
    /**
     * Grid Position field in *Poster → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.grid_position
     * - **Documentation**: https://prismic.io/docs/field#number
     */
    grid_position: prismic.NumberField;
}

/**
 * Primary content in *Poster → Items*
 */
export interface PosterSliceOneUpItem {
    /**
     * Poster Position field in *Poster → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].poster_position
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    poster_position: prismic.KeyTextField;

    /**
     * Desktop Image field in *Poster → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].desktop_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    desktop_image: prismic.ImageField<never>;

    /**
     * Mobile Image field in *Poster → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].mobile_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    mobile_image: prismic.ImageField<never>;

    /**
     * Title field in *Poster → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * Text Theme Desktop field in *Poster → Items*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: poster.items[].text_theme_desktop
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    text_theme_desktop: prismic.BooleanField;

    /**
     * Text Theme Mobile field in *Poster → Items*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: poster.items[].text_theme_mobile
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    text_theme_mobile: prismic.BooleanField;

    /**
     * Button Label field in *Poster → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].button_label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_label: prismic.KeyTextField;

    /**
     * Button Link field in *Poster → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].button_link
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_link: prismic.KeyTextField;

    /**
     * Button Variant field in *Poster → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Text
     * - **API ID Path**: poster.items[].button_variant
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_variant: prismic.SelectField<
        'Text' | 'Base' | 'Secondary' | 'Ghost' | 'Quite',
        'filled'
    >;

    /**
     * Button Icon field in *Poster → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].button_icon
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_icon: prismic.SelectField<
        '-' | 'Northeast' | 'Right' | 'Left' | 'Globe' | 'Discover'
    >;
}

/**
 * One Up variation for Poster Slice
 *
 * - **API ID**: `oneUp`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PosterSliceOneUp = prismic.SharedSliceVariation<
    'oneUp',
    Simplify<PosterSliceOneUpPrimary>,
    Simplify<PosterSliceOneUpItem>
>;

/**
 * Primary content in *Poster → Primary*
 */
export interface PosterSliceTwoUpPrimary {
    /**
     * Grid Position field in *Poster → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.grid_position
     * - **Documentation**: https://prismic.io/docs/field#number
     */
    grid_position: prismic.NumberField;
}

/**
 * Primary content in *Poster → Items*
 */
export interface PosterSliceTwoUpItem {
    /**
     * Poster Position field in *Poster → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].poster_position
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    poster_position: prismic.KeyTextField;

    /**
     * Desktop Image field in *Poster → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].desktop_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    desktop_image: prismic.ImageField<never>;

    /**
     * Mobile Image field in *Poster → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].mobile_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    mobile_image: prismic.ImageField<never>;

    /**
     * Title field in *Poster → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * Text Theme Desktop field in *Poster → Items*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: poster.items[].text_theme_desktop
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    text_theme_desktop: prismic.BooleanField;

    /**
     * Text Theme Mobile field in *Poster → Items*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: poster.items[].text_theme_mobile
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    text_theme_mobile: prismic.BooleanField;

    /**
     * Button Label field in *Poster → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].button_label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_label: prismic.KeyTextField;

    /**
     * Button Link field in *Poster → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].button_link
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_link: prismic.KeyTextField;

    /**
     * Button Variant field in *Poster → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Text
     * - **API ID Path**: poster.items[].button_variant
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_variant: prismic.SelectField<
        'Text' | 'Base' | 'Secondary' | 'Ghost' | 'Quite',
        'filled'
    >;

    /**
     * Button Icon field in *Poster → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].button_icon
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_icon: prismic.SelectField<
        '-' | 'Northeast' | 'Right' | 'Left' | 'Globe' | 'Discover'
    >;
}

/**
 * Two Up variation for Poster Slice
 *
 * - **API ID**: `twoUp`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PosterSliceTwoUp = prismic.SharedSliceVariation<
    'twoUp',
    Simplify<PosterSliceTwoUpPrimary>,
    Simplify<PosterSliceTwoUpItem>
>;

/**
 * Primary content in *Poster → Primary*
 */
export interface PosterSliceFeaturePrimary {
    /**
     * Desktop Image field in *Poster → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.desktop_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    desktop_image: prismic.ImageField<never>;

    /**
     * Mobile Image field in *Poster → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.mobile_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    mobile_image: prismic.ImageField<never>;

    /**
     * Product Title field in *Poster → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.product_title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    product_title: prismic.KeyTextField;

    /**
     * Description field in *Poster → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.description
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    description: prismic.KeyTextField;

    /**
     * Background Colour field in *Poster → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.background_colour
     * - **Documentation**: https://prismic.io/docs/field#color
     */
    background_colour: prismic.ColorField;

    /**
     * Text Theme Desktop field in *Poster → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: poster.primary.text_theme_desktop
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    text_theme_desktop: prismic.BooleanField;

    /**
     * Text Theme Mobile field in *Poster → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: poster.primary.text_theme_mobile
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    text_theme_mobile: prismic.BooleanField;
}

/**
 * Primary content in *Poster → Items*
 */
export interface PosterSliceFeatureItem {
    /**
     * Button Label field in *Poster → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].button_label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_label: prismic.KeyTextField;

    /**
     * Button Link field in *Poster → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].button_link
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_link: prismic.KeyTextField;

    /**
     * Button Variant field in *Poster → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Base
     * - **API ID Path**: poster.items[].button_variant
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_variant: prismic.SelectField<
        'Base' | 'Secondary' | 'Text' | 'Ghost' | 'Quite',
        'filled'
    >;

    /**
     * Button Icon field in *Poster → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].button_icon
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_icon: prismic.SelectField<
        '-' | 'Northeast' | 'Right' | 'Left' | 'Globe' | 'Discover'
    >;
}

/**
 * Feature variation for Poster Slice
 *
 * - **API ID**: `feature`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PosterSliceFeature = prismic.SharedSliceVariation<
    'feature',
    Simplify<PosterSliceFeaturePrimary>,
    Simplify<PosterSliceFeatureItem>
>;

/**
 * Primary content in *Poster → Primary*
 */
export interface PosterSliceFeatureStackPrimary {
    /**
     * Product Title field in *Poster → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.product_title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    product_title: prismic.KeyTextField;

    /**
     * Button 1 Label field in *Poster → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.button_1_label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_1_label: prismic.KeyTextField;

    /**
     * Button 1 Variant field in *Poster → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.button_1_variant
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_1_variant: prismic.SelectField<
        'Secondary' | 'Base' | 'Text' | 'Ghost' | 'Quite'
    >;

    /**
     * Button 1 Link field in *Poster → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.button_1_link
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_1_link: prismic.KeyTextField;

    /**
     * Button 1 Icon field in *Poster → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.button_1_icon
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_1_icon: prismic.SelectField<
        '-' | 'Discover' | 'Globe' | 'Northeast' | 'Right' | 'Left'
    >;

    /**
     * Button 2 Label field in *Poster → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.button_2_label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_2_label: prismic.KeyTextField;

    /**
     * Button 2 Variant field in *Poster → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.button_2_variant
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_2_variant: prismic.SelectField<
        'Secondary' | 'Base' | 'Text' | 'Ghost' | 'Quite'
    >;

    /**
     * Button 2 Link field in *Poster → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.button_2_link
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_2_link: prismic.KeyTextField;

    /**
     * Button 2 Icon field in *Poster → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.button_2_icon
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_2_icon: prismic.SelectField<
        '-' | 'Discover' | 'Globe' | 'Northeast' | 'Right' | 'Left'
    >;

    /**
     * Button 3 Label field in *Poster → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.button_3_label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_3_label: prismic.KeyTextField;

    /**
     * Button 3 Variant field in *Poster → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.button_3_variant
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_3_variant: prismic.SelectField<
        'Secondary' | 'Base' | 'Text' | 'Ghost' | 'Quite'
    >;

    /**
     * Button 3 Link field in *Poster → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.button_3_link
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_3_link: prismic.KeyTextField;

    /**
     * Button 3 Icon field in *Poster → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.button_3_icon
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_3_icon: prismic.SelectField<
        '-' | 'Discover' | 'Globe' | 'Northeast' | 'Right' | 'Left'
    >;

    /**
     * Text Theme Desktop field in *Poster → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: poster.primary.text_theme_desktop
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    text_theme_desktop: prismic.BooleanField;

    /**
     * Text Theme Mobile field in *Poster → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: poster.primary.text_theme_mobile
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    text_theme_mobile: prismic.BooleanField;
}

/**
 * Primary content in *Poster → Items*
 */
export interface PosterSliceFeatureStackItem {
    /**
     * Thumbnail field in *Poster → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].thumbnail
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    thumbnail: prismic.ImageField<never>;

    /**
     * Desktop Image field in *Poster → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].desktop_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    desktop_image: prismic.ImageField<never>;

    /**
     * Mobile Image field in *Poster → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].mobile_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    mobile_image: prismic.ImageField<never>;

    /**
     * Description field in *Poster → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].description
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    description: prismic.KeyTextField;

    /**
     * Background Colour field in *Poster → Items*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].background_colour
     * - **Documentation**: https://prismic.io/docs/field#color
     */
    background_colour: prismic.ColorField;
}

/**
 * Feature Stack variation for Poster Slice
 *
 * - **API ID**: `featureStack`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PosterSliceFeatureStack = prismic.SharedSliceVariation<
    'featureStack',
    Simplify<PosterSliceFeatureStackPrimary>,
    Simplify<PosterSliceFeatureStackItem>
>;

/**
 * Primary content in *Poster → Primary*
 */
export interface PosterSliceFeatureStackVideoPrimary {
    /**
     * Product Title field in *Poster → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.product_title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    product_title: prismic.KeyTextField;

    /**
     * Video Desktop Link field in *Poster → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.video_desktop_link
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    video_desktop_link: prismic.LinkField;

    /**
     * Video Mobile Link field in *Poster → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.video_mobile_link
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    video_mobile_link: prismic.LinkField;

    /**
     * Background Colour field in *Poster → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.background_colour
     * - **Documentation**: https://prismic.io/docs/field#color
     */
    background_colour: prismic.ColorField;

    /**
     * Variant Desktop Image field in *Poster → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.variant_dekstop_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    variant_dekstop_image: prismic.ImageField<never>;

    /**
     * Variant Mobile Image field in *Poster → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.variant_mobile_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    variant_mobile_image: prismic.ImageField<never>;

    /**
     * Variant Title field in *Poster → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.variant_title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    variant_title: prismic.KeyTextField;

    /**
     * Description field in *Poster → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.description
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    description: prismic.KeyTextField;

    /**
     * Text Theme Desktop field in *Poster → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: poster.primary.text_theme_desktop
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    text_theme_desktop: prismic.BooleanField;

    /**
     * Text Theme Mobile field in *Poster → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: poster.primary.text_theme_mobile
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    text_theme_mobile: prismic.BooleanField;
}

/**
 * Primary content in *Poster → Items*
 */
export interface PosterSliceFeatureStackVideoItem {
    /**
     * Button Label field in *Poster → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].button_label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_label: prismic.KeyTextField;

    /**
     * Button Link field in *Poster → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].button_link
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_link: prismic.KeyTextField;

    /**
     * Button Variant field in *Poster → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Base
     * - **API ID Path**: poster.items[].button_variant
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_variant: prismic.SelectField<
        'Base' | 'Secondary' | 'Text' | 'Ghost' | 'Quite',
        'filled'
    >;

    /**
     * Button Icon field in *Poster → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: -
     * - **API ID Path**: poster.items[].button_icon
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_icon: prismic.SelectField<
        '-' | 'Northeast' | 'Right' | 'Left' | 'Globe' | 'Discover',
        'filled'
    >;
}

/**
 * Feature Stack Video variation for Poster Slice
 *
 * - **API ID**: `featureStackVideo`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PosterSliceFeatureStackVideo = prismic.SharedSliceVariation<
    'featureStackVideo',
    Simplify<PosterSliceFeatureStackVideoPrimary>,
    Simplify<PosterSliceFeatureStackVideoItem>
>;

/**
 * Primary content in *Poster → Primary*
 */
export interface PosterSliceFeaturesPrimary {
    /**
     * Background Colour Left field in *Poster → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.background_colour_left
     * - **Documentation**: https://prismic.io/docs/field#color
     */
    background_colour_left: prismic.ColorField;

    /**
     * Desktop Image Left field in *Poster → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.desktop_image_left
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    desktop_image_left: prismic.ImageField<never>;

    /**
     * Mobile Image Left field in *Poster → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.mobile_image_left
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    mobile_image_left: prismic.ImageField<never>;

    /**
     * Background Colour Right field in *Poster → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.background_colour_right
     * - **Documentation**: https://prismic.io/docs/field#color
     */
    background_colour_right: prismic.ColorField;

    /**
     * Desktop Image Right field in *Poster → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.desktop_image_right
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    desktop_image_right: prismic.ImageField<never>;

    /**
     * Mobile Image Right field in *Poster → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.mobile_image_right
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    mobile_image_right: prismic.ImageField<never>;

    /**
     * Context field in *Poster → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.context
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    context: prismic.KeyTextField;

    /**
     * Title field in *Poster → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * Description field in *Poster → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.description
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    description: prismic.KeyTextField;

    /**
     * Title Position field in *Poster → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.title_position
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    title_position: prismic.SelectField<'Top' | 'Bottom'>;

    /**
     * Text Theme Desktop field in *Poster → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: poster.primary.text_theme_desktop
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    text_theme_desktop: prismic.BooleanField;

    /**
     * Text Theme Mobile field in *Poster → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: poster.primary.text_theme_mobile
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    text_theme_mobile: prismic.BooleanField;
}

/**
 * Primary content in *Poster → Items*
 */
export interface PosterSliceFeaturesItem {
    /**
     * Button Variant field in *Poster → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Base
     * - **API ID Path**: poster.items[].button_variant
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_variant: prismic.SelectField<
        'Base' | 'Secondary' | 'Text' | 'Ghost' | 'Quite',
        'filled'
    >;

    /**
     * Button Label field in *Poster → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].button_label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_label: prismic.KeyTextField;

    /**
     * Button Link field in *Poster → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].button_link
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_link: prismic.KeyTextField;

    /**
     * Button Icon field in *Poster → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].button_icon
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_icon: prismic.SelectField<
        '-' | 'Northeast' | 'Right' | 'Left' | 'Globe' | 'Discover'
    >;
}

/**
 * Features variation for Poster Slice
 *
 * - **API ID**: `features`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PosterSliceFeatures = prismic.SharedSliceVariation<
    'features',
    Simplify<PosterSliceFeaturesPrimary>,
    Simplify<PosterSliceFeaturesItem>
>;

/**
 * Primary content in *Poster → Primary*
 */
export interface PosterSliceFeaturesAltPrimary {
    /**
     * Background Colour Left field in *Poster → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.background_colour_left
     * - **Documentation**: https://prismic.io/docs/field#color
     */
    background_colour_left: prismic.ColorField;

    /**
     * Desktop Image Left field in *Poster → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.desktop_image_left
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    desktop_image_left: prismic.ImageField<never>;

    /**
     * Mobile Image Left field in *Poster → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.mobile_image_left
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    mobile_image_left: prismic.ImageField<never>;

    /**
     * Background Colour Right field in *Poster → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.background_colour_right
     * - **Documentation**: https://prismic.io/docs/field#color
     */
    background_colour_right: prismic.ColorField;

    /**
     * Desktop Image Right field in *Poster → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.desktop_image_right
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    desktop_image_right: prismic.ImageField<never>;

    /**
     * Mobile Image Right field in *Poster → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.mobile_image_right
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    mobile_image_right: prismic.ImageField<never>;

    /**
     * Context field in *Poster → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.primary.context
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    context: prismic.KeyTextField;

    /**
     * Text Theme Desktop field in *Poster → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: poster.primary.text_theme_desktop
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    text_theme_desktop: prismic.BooleanField;

    /**
     * Text Theme Mobile field in *Poster → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: poster.primary.text_theme_mobile
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    text_theme_mobile: prismic.BooleanField;
}

/**
 * Primary content in *Poster → Items*
 */
export interface PosterSliceFeaturesAltItem {
    /**
     * Button Placement field in *Poster → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].button_placement
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_placement: prismic.SelectField<'Left' | 'Right'>;

    /**
     * Button Variant field in *Poster → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Base
     * - **API ID Path**: poster.items[].button_variant
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_variant: prismic.SelectField<
        'Base' | 'Secondary' | 'Text' | 'Ghost' | 'Quite',
        'filled'
    >;

    /**
     * Button Label field in *Poster → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].button_label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_label: prismic.KeyTextField;

    /**
     * Button Link field in *Poster → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].button_link
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_link: prismic.KeyTextField;

    /**
     * Button Icon field in *Poster → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: poster.items[].button_icon
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_icon: prismic.SelectField<
        '-' | 'Northeast' | 'Right' | 'Left' | 'Globe' | 'Discover'
    >;
}

/**
 * Features Alt variation for Poster Slice
 *
 * - **API ID**: `featuresAlt`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PosterSliceFeaturesAlt = prismic.SharedSliceVariation<
    'featuresAlt',
    Simplify<PosterSliceFeaturesAltPrimary>,
    Simplify<PosterSliceFeaturesAltItem>
>;

/**
 * Slice variation for *Poster*
 */
type PosterSliceVariation =
    | PosterSliceOneUp
    | PosterSliceTwoUp
    | PosterSliceFeature
    | PosterSliceFeatureStack
    | PosterSliceFeatureStackVideo
    | PosterSliceFeatures
    | PosterSliceFeaturesAlt;

/**
 * Poster Shared Slice
 *
 * - **API ID**: `poster`
 * - **Description**: Poster
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PosterSlice = prismic.SharedSlice<'poster', PosterSliceVariation>;

/**
 * Primary content in *Swiper → Primary*
 */
export interface SwiperSliceProductFeaturePrimary {
    /**
     * Context field in *Swiper → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.primary.context
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    context: prismic.KeyTextField;
}

/**
 * Primary content in *Swiper → Items*
 */
export interface SwiperSliceProductFeatureItem {
    /**
     * Desktop Image field in *Swiper → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.items[].desktop_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    desktop_image: prismic.ImageField<never>;

    /**
     * Mobile Image field in *Swiper → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.items[].mobile_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    mobile_image: prismic.ImageField<never>;

    /**
     * Description field in *Swiper → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.items[].description
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    description: prismic.KeyTextField;
}

/**
 * Product Feature variation for Swiper Slice
 *
 * - **API ID**: `product_feature`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SwiperSliceProductFeature = prismic.SharedSliceVariation<
    'product_feature',
    Simplify<SwiperSliceProductFeaturePrimary>,
    Simplify<SwiperSliceProductFeatureItem>
>;

/**
 * Primary content in *Swiper → Primary*
 */
export interface SwiperSliceProductShopifyPrimary {
    /**
     * Context field in *Swiper → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.primary.context
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    context: prismic.KeyTextField;

    /**
     * Collection Handle field in *Swiper → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.primary.collection_handle
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    collection_handle: prismic.KeyTextField;
}

/**
 * Product Shopify variation for Swiper Slice
 *
 * - **API ID**: `product_shopify`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SwiperSliceProductShopify = prismic.SharedSliceVariation<
    'product_shopify',
    Simplify<SwiperSliceProductShopifyPrimary>,
    never
>;

/**
 * Primary content in *Swiper → Primary*
 */
export interface SwiperSliceCollectionPrimary {
    /**
     * Context field in *Swiper → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.primary.context
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    context: prismic.KeyTextField;
}

/**
 * Primary content in *Swiper → Items*
 */
export interface SwiperSliceCollectionItem {
    /**
     * Desktop Image field in *Swiper → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.items[].desktop_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    desktop_image: prismic.ImageField<never>;

    /**
     * Mobile Image field in *Swiper → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.items[].mobile_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    mobile_image: prismic.ImageField<never>;

    /**
     * Context field in *Swiper → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Context
     * - **API ID Path**: swiper.items[].context
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    context: prismic.KeyTextField;

    /**
     * Title field in *Swiper → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: MAAP X 100% EYEWEAR
     * - **API ID Path**: swiper.items[].title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * Button Label field in *Swiper → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Discover
     * - **API ID Path**: swiper.items[].button_label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_label: prismic.KeyTextField;

    /**
     * Link field in *Swiper → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: /collections/new-arrivals
     * - **API ID Path**: swiper.items[].link
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    link: prismic.KeyTextField;

    /**
     * Button Variant field in *Swiper → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Secondary
     * - **API ID Path**: swiper.items[].button_variant
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_variant: prismic.SelectField<
        'Secondary' | 'Base' | 'Ghost' | 'Quite' | 'Text',
        'filled'
    >;

    /**
     * Button Icon field in *Swiper → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.items[].button_icon
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_icon: prismic.SelectField<
        '-' | 'Discover' | 'Globe' | 'Northeast' | 'Left' | 'Right'
    >;
}

/**
 * Collection variation for Swiper Slice
 *
 * - **API ID**: `collection`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SwiperSliceCollection = prismic.SharedSliceVariation<
    'collection',
    Simplify<SwiperSliceCollectionPrimary>,
    Simplify<SwiperSliceCollectionItem>
>;

/**
 * Primary content in *Swiper → Primary*
 */
export interface SwiperSliceProductSkuFeaturePrimary {
    /**
     * Context field in *Swiper → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.primary.context
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    context: prismic.KeyTextField;

    /**
     * Title field in *Swiper → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;
}

/**
 * Primary content in *Swiper → Items*
 */
export interface SwiperSliceProductSkuFeatureItem {
    /**
     * Handle field in *Swiper → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: alt-road-jersey-stargazer
     * - **API ID Path**: swiper.items[].handle
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    handle: prismic.KeyTextField;
}

/**
 * Product SKU Feature variation for Swiper Slice
 *
 * - **API ID**: `product_sku_feature`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SwiperSliceProductSkuFeature = prismic.SharedSliceVariation<
    'product_sku_feature',
    Simplify<SwiperSliceProductSkuFeaturePrimary>,
    Simplify<SwiperSliceProductSkuFeatureItem>
>;

/**
 * Primary content in *Swiper → Primary*
 */
export interface SwiperSliceCapsulePrimary {
    /**
     * Context field in *Swiper → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.primary.context
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    context: prismic.KeyTextField;
}

/**
 * Primary content in *Swiper → Items*
 */
export interface SwiperSliceCapsuleItem {
    /**
     * Desktop Image field in *Swiper → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.items[].desktop_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    desktop_image: prismic.ImageField<never>;

    /**
     * Mobile Image field in *Swiper → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.items[].mobile_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    mobile_image: prismic.ImageField<never>;

    /**
     * Button Label field in *Swiper → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Call to Action
     * - **API ID Path**: swiper.items[].button_label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_label: prismic.KeyTextField;

    /**
     * Link field in *Swiper → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.items[].link
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    link: prismic.KeyTextField;

    /**
     * Button Variant field in *Swiper → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Text
     * - **API ID Path**: swiper.items[].button_variant
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_variant: prismic.SelectField<
        'Text' | 'Base' | 'Secondary' | 'Ghost' | 'Quite',
        'filled'
    >;

    /**
     * Button Icon field in *Swiper → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.items[].button_icon
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_icon: prismic.SelectField<
        '-' | 'Northeast' | 'Right' | 'Left' | 'Discover' | 'Globe'
    >;
}

/**
 * Capsule variation for Swiper Slice
 *
 * - **API ID**: `capsule`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SwiperSliceCapsule = prismic.SharedSliceVariation<
    'capsule',
    Simplify<SwiperSliceCapsulePrimary>,
    Simplify<SwiperSliceCapsuleItem>
>;

/**
 * Primary content in *Swiper → Primary*
 */
export interface SwiperSliceProductFlatlaySingleCollectionPrimary {
    /**
     * Context field in *Swiper → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.primary.context
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    context: prismic.KeyTextField;

    /**
     * Title field in *Swiper → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * Description field in *Swiper → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.primary.description
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    description: prismic.KeyTextField;

    /**
     * Collection Handle field in *Swiper → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.primary.collection_handle
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    collection_handle: prismic.KeyTextField;
}

/**
 * Primary content in *Swiper → Items*
 */
export interface SwiperSliceProductFlatlaySingleCollectionItem {
    /**
     * Button Label field in *Swiper → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.items[].button_label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_label: prismic.KeyTextField;

    /**
     * Button Link field in *Swiper → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: /collections/new-arrivals
     * - **API ID Path**: swiper.items[].button_link
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_link: prismic.KeyTextField;

    /**
     * Button Variant field in *Swiper → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.items[].button_variant
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_variant: prismic.SelectField<
        'Base' | 'Secondary' | 'Ghost' | 'Text' | 'Quite'
    >;

    /**
     * Button Icon field in *Swiper → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.items[].button_icon
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_icon: prismic.SelectField<
        '-' | 'Globe' | 'Discover' | 'Northeast' | 'Right' | 'Left'
    >;
}

/**
 * Product Flatlay Single Collection variation for Swiper Slice
 *
 * - **API ID**: `product_flatlay_single_collection`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SwiperSliceProductFlatlaySingleCollection =
    prismic.SharedSliceVariation<
        'product_flatlay_single_collection',
        Simplify<SwiperSliceProductFlatlaySingleCollectionPrimary>,
        Simplify<SwiperSliceProductFlatlaySingleCollectionItem>
    >;

/**
 * Primary content in *Swiper → Primary*
 */
export interface SwiperSliceProductFlatlayTabbedCollectionsPrimary {
    /**
     * Context field in *Swiper → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.primary.context
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    context: prismic.KeyTextField;
}

/**
 * Primary content in *Swiper → Items*
 */
export interface SwiperSliceProductFlatlayTabbedCollectionsItem {
    /**
     * Collection Handle field in *Swiper → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.items[].collection_handle
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    collection_handle: prismic.KeyTextField;

    /**
     * Description field in *Swiper → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.items[].description
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    description: prismic.KeyTextField;

    /**
     * Button 1 Label field in *Swiper → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.items[].button_1_label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_1_label: prismic.KeyTextField;

    /**
     * Button 1 Link field in *Swiper → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: /collections/new-arrivals
     * - **API ID Path**: swiper.items[].button_1_link
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_1_link: prismic.KeyTextField;

    /**
     * Button 1 Variant field in *Swiper → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Secondary
     * - **API ID Path**: swiper.items[].button_1_variant
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_1_variant: prismic.SelectField<
        'Secondary' | 'Base' | 'Ghost' | 'Text' | 'Quite',
        'filled'
    >;

    /**
     * Button 1 Icon field in *Swiper → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.items[].button_1_icon
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_1_icon: prismic.SelectField<
        '-' | 'Discover' | 'Globe' | 'Northeast' | 'Left' | 'Right'
    >;

    /**
     * Button 2 Label field in *Swiper → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.items[].button_2_label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_2_label: prismic.KeyTextField;

    /**
     * Button 2 Link field in *Swiper → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: /collections/new-arrivals
     * - **API ID Path**: swiper.items[].button_2_link
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_2_link: prismic.KeyTextField;

    /**
     * Button 2 Variant field in *Swiper → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Secondary
     * - **API ID Path**: swiper.items[].button_2_variant
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_2_variant: prismic.SelectField<
        'Secondary' | 'Base' | 'Ghost' | 'Text' | 'Quite',
        'filled'
    >;

    /**
     * Button 2 Icon field in *Swiper → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.items[].button_2_icon
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_2_icon: prismic.SelectField<
        '-' | 'Discover' | 'Globe' | 'Northeast' | 'Right' | 'Left'
    >;

    /**
     * Button 3 Label field in *Swiper → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.items[].button_3_label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_3_label: prismic.KeyTextField;

    /**
     * Button 3 Link field in *Swiper → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.items[].button_3_link
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_3_link: prismic.KeyTextField;

    /**
     * Button 3 Variant field in *Swiper → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Base
     * - **API ID Path**: swiper.items[].button_3_variant
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_3_variant: prismic.SelectField<
        'Base' | 'Secondary' | 'Ghost' | 'Text' | 'Quite',
        'filled'
    >;

    /**
     * Button 3 Icon field in *Swiper → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: swiper.items[].button_3_icon
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_3_icon: prismic.SelectField<
        '-' | 'Discover' | 'Globe' | 'Northeast' | 'Right' | 'Left'
    >;
}

/**
 * Product Flatlay Tabbed Collections variation for Swiper Slice
 *
 * - **API ID**: `product_flatlay_tabbed_collections`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SwiperSliceProductFlatlayTabbedCollections =
    prismic.SharedSliceVariation<
        'product_flatlay_tabbed_collections',
        Simplify<SwiperSliceProductFlatlayTabbedCollectionsPrimary>,
        Simplify<SwiperSliceProductFlatlayTabbedCollectionsItem>
    >;

/**
 * Slice variation for *Swiper*
 */
type SwiperSliceVariation =
    | SwiperSliceProductFeature
    | SwiperSliceProductShopify
    | SwiperSliceCollection
    | SwiperSliceProductSkuFeature
    | SwiperSliceCapsule
    | SwiperSliceProductFlatlaySingleCollection
    | SwiperSliceProductFlatlayTabbedCollections;

/**
 * Swiper Shared Slice
 *
 * - **API ID**: `swiper`
 * - **Description**: Swiper
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SwiperSlice = prismic.SharedSlice<'swiper', SwiperSliceVariation>;

declare module '@prismicio/client' {
    interface CreateClient {
        (
            repositoryNameOrEndpoint: string,
            options?: prismic.ClientConfig
        ): prismic.Client<AllDocumentTypes>;
    }

    namespace Content {
        export type {
            CollectionDocument,
            CollectionDocumentData,
            CollectionDocumentDataSlicesSlice,
            CollectionDocumentDataSlices2Slice,
            CollectionDocumentDataSlices3Slice,
            CollectionDocumentDataSlices4Slice,
            ContentLibraryDocument,
            ContentLibraryDocumentData,
            ContentLibraryDocumentDataSlicesSlice,
            LandingPageDocument,
            LandingPageDocumentData,
            LandingPageDocumentDataSlicesSlice,
            ProductDocument,
            ProductDocumentData,
            ProductDocumentDataSlicesSlice,
            ProductInformationDocument,
            ProductInformationDocumentData,
            AllDocumentTypes,
            BillboardSlice,
            BillboardSliceStaticPrimary,
            BillboardSliceStaticItem,
            BillboardSliceCarouselItem,
            BillboardSliceVariation,
            BillboardSliceStatic,
            BillboardSliceCarousel,
            CtaBannerSlice,
            CtaBannerSliceSinglePrimary,
            CtaBannerSliceSplitItem,
            CtaBannerSliceVariation,
            CtaBannerSliceSingle,
            CtaBannerSliceSplit,
            IntroSlice,
            IntroSliceDefaultPrimary,
            IntroSliceVariation,
            IntroSliceDefault,
            LookbookSlice,
            LookbookSliceDefaultPrimary,
            LookbookSliceDefaultItem,
            LookbookSliceVariation,
            LookbookSliceDefault,
            PosterSlice,
            PosterSliceOneUpPrimary,
            PosterSliceOneUpItem,
            PosterSliceTwoUpPrimary,
            PosterSliceTwoUpItem,
            PosterSliceFeaturePrimary,
            PosterSliceFeatureItem,
            PosterSliceFeatureStackPrimary,
            PosterSliceFeatureStackItem,
            PosterSliceFeatureStackVideoPrimary,
            PosterSliceFeatureStackVideoItem,
            PosterSliceFeaturesPrimary,
            PosterSliceFeaturesItem,
            PosterSliceFeaturesAltPrimary,
            PosterSliceFeaturesAltItem,
            PosterSliceVariation,
            PosterSliceOneUp,
            PosterSliceTwoUp,
            PosterSliceFeature,
            PosterSliceFeatureStack,
            PosterSliceFeatureStackVideo,
            PosterSliceFeatures,
            PosterSliceFeaturesAlt,
            SwiperSlice,
            SwiperSliceProductFeaturePrimary,
            SwiperSliceProductFeatureItem,
            SwiperSliceProductShopifyPrimary,
            SwiperSliceCollectionPrimary,
            SwiperSliceCollectionItem,
            SwiperSliceProductSkuFeaturePrimary,
            SwiperSliceProductSkuFeatureItem,
            SwiperSliceCapsulePrimary,
            SwiperSliceCapsuleItem,
            SwiperSliceProductFlatlaySingleCollectionPrimary,
            SwiperSliceProductFlatlaySingleCollectionItem,
            SwiperSliceProductFlatlayTabbedCollectionsPrimary,
            SwiperSliceProductFlatlayTabbedCollectionsItem,
            SwiperSliceVariation,
            SwiperSliceProductFeature,
            SwiperSliceProductShopify,
            SwiperSliceCollection,
            SwiperSliceProductSkuFeature,
            SwiperSliceCapsule,
            SwiperSliceProductFlatlaySingleCollection,
            SwiperSliceProductFlatlayTabbedCollections,
        };
    }
}
