name: "Chromatic Deployment"

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/checkout@v1
      - run: pnpm i && cd apps/storybook && pnpm i
      - uses: chromaui/action@v1
        with:
          workingDir: apps/storybook
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}